version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "80:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
